export const ICONS = [
  'alarm',
  'archive',
  'arrow-clockwise',
  'bank',
  'basket',
  'bell',
  'box',
  'bicycle',
  'brightness-alt-high',
  'briefcase',
  'brightness-high',
  'bucket',
  'brush',
  'calendar3',
  'camera',
  'camera-reels',
  'cart',
  'cash',
  'cash-coin',
  'chat-dots',
  'clipboard',
  'clock',
  'cone-striped',
  'controller',
  'compass',
  'credit-card',
  'credit-card2-back',
  'credit-card2-back-fill',
  'credit-card2-front',
  'currency-dollar',
  'currency-bitcoin',
  'currency-exchange',
  'dash-circle',
  'droplet',
  'emoji-smile',
  'emoji-wink',
  'emoji-neutral',
  'emoji-heart-eyes',
  'emoji-expressionless',
  'emoji-frown',
  'envelope',
  'exclamation-circle',
  'eyeglasses',
  'file-earmark-zip',
  'file-earmark',
  'gem',
  'geo-fill',
  'handbag',
  'headset',
  'heart',
  'house',
  'images',
  'instagram',
  'mailbox',
  'lock-fill',
  'minecart-loaded',
  'moon-stars',
  'music-note',
  'palette',
  'people',
  'phone',
  'piggy-bank',
  'plug',
  'printer',
  'star',
  'suit-heart',
  'telephone',
  'trash',
  'umbrella',
  'watch',
  'percent',
  'signpost',
  'smartwatch'
]

export const DAYS_WEEK = new Map([
  [1, 'Lunes'],
  [2, 'Martes'],
  [3, 'Miercoles'],
  [4, 'Jueves'],
  [5, 'Viernes'],
  [6, 'Sábado'],
  [0, 'Domingo']
])

export function daysWeekToString (day) {
  return DAYS_WEEK.get(day)
}

export const MONTHS = new Map([
  [1, 'Enero'],
  [2, 'Febrero'],
  [3, 'Marzo'],
  [4, 'Abril'],
  [5, 'Mayo'],
  [6, 'Junio'],
  [7, 'Julio'],
  [8, 'Agosto'],
  [9, 'Septiembre'],
  [10, 'Octubre'],
  [11, 'Noviembre'],
  [12, 'Diciembre']
])

export function monthsToString (month) {
  return MONTHS.get(month)
}
